/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthProfileRouteImport } from './routes/_auth/profile'
import { Route as AuthNotificationsRouteImport } from './routes/_auth/notifications'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthConnectionsRouteImport } from './routes/_auth/connections'
import { Route as AuthBrowseRouteImport } from './routes/_auth/browse'
import { Route as AuthStudentRouteImport } from './routes/_auth/_student'
import { Route as AuthPgownerRouteImport } from './routes/_auth/_pgowner'
import { Route as AuthListingIdRouteImport } from './routes/_auth/listing.$id'
import { Route as AuthStudentSavedRouteImport } from './routes/_auth/_student/saved'
import { Route as AuthStudentPreferencesRouteImport } from './routes/_auth/_student/preferences'
import { Route as AuthStudentInterestsRouteImport } from './routes/_auth/_student/interests'
import { Route as AuthPgownerPropertiesRouteImport } from './routes/_auth/_pgowner/properties'
import { Route as AuthPgownerListingsRouteImport } from './routes/_auth/_pgowner/listings'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthProfileRoute = AuthProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthRoute,
} as any)
const AuthNotificationsRoute = AuthNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthConnectionsRoute = AuthConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => AuthRoute,
} as any)
const AuthBrowseRoute = AuthBrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => AuthRoute,
} as any)
const AuthStudentRoute = AuthStudentRouteImport.update({
  id: '/_student',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPgownerRoute = AuthPgownerRouteImport.update({
  id: '/_pgowner',
  getParentRoute: () => AuthRoute,
} as any)
const AuthListingIdRoute = AuthListingIdRouteImport.update({
  id: '/listing/$id',
  path: '/listing/$id',
  getParentRoute: () => AuthRoute,
} as any)
const AuthStudentSavedRoute = AuthStudentSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AuthStudentRoute,
} as any)
const AuthStudentPreferencesRoute = AuthStudentPreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => AuthStudentRoute,
} as any)
const AuthStudentInterestsRoute = AuthStudentInterestsRouteImport.update({
  id: '/interests',
  path: '/interests',
  getParentRoute: () => AuthStudentRoute,
} as any)
const AuthPgownerPropertiesRoute = AuthPgownerPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => AuthPgownerRoute,
} as any)
const AuthPgownerListingsRoute = AuthPgownerListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => AuthPgownerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/browse': typeof AuthBrowseRoute
  '/connections': typeof AuthConnectionsRoute
  '/dashboard': typeof AuthDashboardRoute
  '/notifications': typeof AuthNotificationsRoute
  '/profile': typeof AuthProfileRoute
  '/listings': typeof AuthPgownerListingsRoute
  '/properties': typeof AuthPgownerPropertiesRoute
  '/interests': typeof AuthStudentInterestsRoute
  '/preferences': typeof AuthStudentPreferencesRoute
  '/saved': typeof AuthStudentSavedRoute
  '/listing/$id': typeof AuthListingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/browse': typeof AuthBrowseRoute
  '/connections': typeof AuthConnectionsRoute
  '/dashboard': typeof AuthDashboardRoute
  '/notifications': typeof AuthNotificationsRoute
  '/profile': typeof AuthProfileRoute
  '/listings': typeof AuthPgownerListingsRoute
  '/properties': typeof AuthPgownerPropertiesRoute
  '/interests': typeof AuthStudentInterestsRoute
  '/preferences': typeof AuthStudentPreferencesRoute
  '/saved': typeof AuthStudentSavedRoute
  '/listing/$id': typeof AuthListingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_auth/_pgowner': typeof AuthPgownerRouteWithChildren
  '/_auth/_student': typeof AuthStudentRouteWithChildren
  '/_auth/browse': typeof AuthBrowseRoute
  '/_auth/connections': typeof AuthConnectionsRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/notifications': typeof AuthNotificationsRoute
  '/_auth/profile': typeof AuthProfileRoute
  '/_auth/_pgowner/listings': typeof AuthPgownerListingsRoute
  '/_auth/_pgowner/properties': typeof AuthPgownerPropertiesRoute
  '/_auth/_student/interests': typeof AuthStudentInterestsRoute
  '/_auth/_student/preferences': typeof AuthStudentPreferencesRoute
  '/_auth/_student/saved': typeof AuthStudentSavedRoute
  '/_auth/listing/$id': typeof AuthListingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/register'
    | '/browse'
    | '/connections'
    | '/dashboard'
    | '/notifications'
    | '/profile'
    | '/listings'
    | '/properties'
    | '/interests'
    | '/preferences'
    | '/saved'
    | '/listing/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/register'
    | '/browse'
    | '/connections'
    | '/dashboard'
    | '/notifications'
    | '/profile'
    | '/listings'
    | '/properties'
    | '/interests'
    | '/preferences'
    | '/saved'
    | '/listing/$id'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/about'
    | '/login'
    | '/register'
    | '/_auth/_pgowner'
    | '/_auth/_student'
    | '/_auth/browse'
    | '/_auth/connections'
    | '/_auth/dashboard'
    | '/_auth/notifications'
    | '/_auth/profile'
    | '/_auth/_pgowner/listings'
    | '/_auth/_pgowner/properties'
    | '/_auth/_student/interests'
    | '/_auth/_student/preferences'
    | '/_auth/_student/saved'
    | '/_auth/listing/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/profile': {
      id: '/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthProfileRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/notifications': {
      id: '/_auth/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthNotificationsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/connections': {
      id: '/_auth/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof AuthConnectionsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/browse': {
      id: '/_auth/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof AuthBrowseRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/_student': {
      id: '/_auth/_student'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthStudentRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/_pgowner': {
      id: '/_auth/_pgowner'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthPgownerRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/listing/$id': {
      id: '/_auth/listing/$id'
      path: '/listing/$id'
      fullPath: '/listing/$id'
      preLoaderRoute: typeof AuthListingIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/_student/saved': {
      id: '/_auth/_student/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof AuthStudentSavedRouteImport
      parentRoute: typeof AuthStudentRoute
    }
    '/_auth/_student/preferences': {
      id: '/_auth/_student/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof AuthStudentPreferencesRouteImport
      parentRoute: typeof AuthStudentRoute
    }
    '/_auth/_student/interests': {
      id: '/_auth/_student/interests'
      path: '/interests'
      fullPath: '/interests'
      preLoaderRoute: typeof AuthStudentInterestsRouteImport
      parentRoute: typeof AuthStudentRoute
    }
    '/_auth/_pgowner/properties': {
      id: '/_auth/_pgowner/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof AuthPgownerPropertiesRouteImport
      parentRoute: typeof AuthPgownerRoute
    }
    '/_auth/_pgowner/listings': {
      id: '/_auth/_pgowner/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof AuthPgownerListingsRouteImport
      parentRoute: typeof AuthPgownerRoute
    }
  }
}

interface AuthPgownerRouteChildren {
  AuthPgownerListingsRoute: typeof AuthPgownerListingsRoute
  AuthPgownerPropertiesRoute: typeof AuthPgownerPropertiesRoute
}

const AuthPgownerRouteChildren: AuthPgownerRouteChildren = {
  AuthPgownerListingsRoute: AuthPgownerListingsRoute,
  AuthPgownerPropertiesRoute: AuthPgownerPropertiesRoute,
}

const AuthPgownerRouteWithChildren = AuthPgownerRoute._addFileChildren(
  AuthPgownerRouteChildren,
)

interface AuthStudentRouteChildren {
  AuthStudentInterestsRoute: typeof AuthStudentInterestsRoute
  AuthStudentPreferencesRoute: typeof AuthStudentPreferencesRoute
  AuthStudentSavedRoute: typeof AuthStudentSavedRoute
}

const AuthStudentRouteChildren: AuthStudentRouteChildren = {
  AuthStudentInterestsRoute: AuthStudentInterestsRoute,
  AuthStudentPreferencesRoute: AuthStudentPreferencesRoute,
  AuthStudentSavedRoute: AuthStudentSavedRoute,
}

const AuthStudentRouteWithChildren = AuthStudentRoute._addFileChildren(
  AuthStudentRouteChildren,
)

interface AuthRouteChildren {
  AuthPgownerRoute: typeof AuthPgownerRouteWithChildren
  AuthStudentRoute: typeof AuthStudentRouteWithChildren
  AuthBrowseRoute: typeof AuthBrowseRoute
  AuthConnectionsRoute: typeof AuthConnectionsRoute
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthNotificationsRoute: typeof AuthNotificationsRoute
  AuthProfileRoute: typeof AuthProfileRoute
  AuthListingIdRoute: typeof AuthListingIdRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthPgownerRoute: AuthPgownerRouteWithChildren,
  AuthStudentRoute: AuthStudentRouteWithChildren,
  AuthBrowseRoute: AuthBrowseRoute,
  AuthConnectionsRoute: AuthConnectionsRoute,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthNotificationsRoute: AuthNotificationsRoute,
  AuthProfileRoute: AuthProfileRoute,
  AuthListingIdRoute: AuthListingIdRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
